export type CategoryRule = {
  defaultMain: string;
  mainCategories: string[];
  subCategories: string[];
  instructions: string;
};

export type CategoryRuleWebsite = {
  name?: string;
  url?: string | null;
};

export const WEBSITE_RULES: Record<string, CategoryRule> = {
  "managingghana.com": {
    defaultMain: "Home",
    mainCategories: ["Home"],
    subCategories: [
      "Business & Finance",
      "Banking and Finance",
      "Fintech",
      "Insurance",
      "Business",
      "Market",
      "Commodity",
      "Economy",
      "Fundraising",
      "Entrepreneurship",
      "Youth Entrepreneurship",
      "Industry & Economic Sectors",
      "Agribusiness",
      "Energy",
      "Ecommerce",
      "Education",
      "Technology",
      "ICT",
      "Telecom",
      "Artificial Intelligence (AI)",
      "Cyber Security",
      "Robotics",
      "Society & Development",
      "Daily Impact",
      "Women Led Businesses",
      "Your Health Matters",
      "Sustainability",
      "Environment",
      "Lifestyle & Other",
      "Lifestyle and Travel",
      "Tourism",
      "Entertainment",
      "Sports",
      "What's On",
      "How To Spend",
      "Days of Our Lives",
      "Expat Communities in Ghana",
      "Home",
      "Other",
      "Legal Affairs",
      "Level Up",
      "Uncategorized",
    ],
    instructions:
      "Main Category is always Home. Do not use Uncategorized. Pick up to 3 secondary categories based on the article's subject, not just the company mentioned.",
  },
  "managingnigeria.com": {
    defaultMain: "Home",
    mainCategories: ["Home"],
    subCategories: [
      "Education",
      "Youth Entrepreneurship",
      "Home",
      "Agribusiness",
      "Banking and Finance",
      "Cryptocurrency",
      "Business",
      "Daily Impact",
      "Days of Our Lives",
      "Ecommerce",
      "Economy",
      "Energy",
      "Entertainment",
      "Entrepreneurship",
      "Environment",
      "Food& Drink",
      "Fundraising",
      "Health",
      "How To Spend",
      "Inspiration",
      "Legal Affairs",
      "Lifestyle",
      "Politics",
      "Sustainability",
      "Technology",
      "Artificial Intelligence (AI)",
      "ICT",
      "Robotics",
      "Telecom",
      "Travel",
      "Uncategorized",
      "Women Led Businesses",
      "Your Health Matters",
    ],
    instructions:
      "Main Category is always Home. Do not use Uncategorized. Choose up to 3 relevant sub categories based on the article subject.",
  },
  "surveillanceafrica.com": {
    defaultMain: "Headline",
    mainCategories: [
      "Headline",
      "Making the news",
      "Startup and Funding",
      "Investor Activity",
      "Scramble For Africa",
    ],
    subCategories: [
      "Education",
      "Headline",
      "Africa",
      "Agribusiness",
      "agriculture",
      "Artificial Intelligence",
      "Asia",
      "Auto",
      "Banking and Finance",
      "Bitcoin",
      "Business",
      "Car Insurance",
      "Climate Change",
      "Cocoa",
      "commodity",
      "Countries",
      "Algeria",
      "Angola",
      "Burkina Faso",
      "Cameroon",
      "Egypt",
      "Ethiopia",
      "Ghana",
      "Ivory Coast",
      "Kenya",
      "Mali",
      "Mauritius",
      "Niger",
      "Nigeria",
      "Senegal",
      "South Africa",
      "Tanzania",
      "Togo",
      "Zimbabwe",
      "Crypto Currency",
      "Decorating",
      "Design",
      "Interiors",
      "Make it Modern",
      "Digital Currency",
      "Ecommerce",
      "Economy",
      "employment",
      "Energy",
      "Entrepreneurship",
      "Environment",
      "Events",
      "Fashion",
      "Featured",
      "finance",
      "fintech",
      "Gadgets",
      "Global 360",
      "Germany",
      "Philippines",
      "United Arab Emirates (UAE)",
      "Health and Wellness",
      "How To Spend",
      "Credit Cards",
      "Property and Mortgages",
      "Hydroelectricity",
      "Insurance",
      "Investor Activity",
      "Israel",
      "Jobs & Opportunities",
      "Jobs",
      "Leadership",
      "Level Up",
      "Life Insurance",
      "Lifestyle",
      "Recipes",
      "Travel",
      "Water Life",
      "local",
      "Making the news",
      "Markets",
      "Mining",
      "Mobile Phones",
      "Music",
      "News",
      "On The Ground",
      "Opportunity",
      "Opportunity and Scholarships",
      "scholarship",
      "People and Culture",
      "Expat Communities In Ghana",
      "Photography",
      "Remote Working",
      "Renewable Energy",
      "Nuclear Energy",
      "Solar",
      "Scramble For Africa",
      "China",
      "Italy",
      "United Kingdom",
      "United States",
      "SMEs",
      "Sport",
      "Startup and Funding",
      "Stock Market",
      "Surveillance Africa",
      "Sustainability",
      "Food Security",
      "Technology",
      "Mobile Money",
      "Telecom",
      "Travel In Style",
      "Video",
      "Volta Region - Ho",
      "What’s On",
      "Creative",
      "Culture",
      "Entertainment",
      "Why Africa",
      "Women With Skills",
    ],
    instructions:
      "Pick 1-2 main categories from Headline, Making the news, Startup and Funding, Investor Activity, Scramble For Africa. Making the news should have at least 4 articles in a large batch. Scramble For Africa is for foreign entities entering Africa. Use up to 3 secondary categories and never use Uncategorized.",
  },
  "surveillanceghana.com": {
    defaultMain: "Headline",
    mainCategories: [
      "Headline",
      "Making the news",
      "Startup and Funding",
      "Investor Activity",
      "Scramble For Africa",
    ],
    subCategories: [
      "Headline",
      "Africa",
      "Agribusiness",
      "agriculture",
      "America",
      "Artificial Intelligence",
      "Asia",
      "Singapore",
      "Auto",
      "Banking and Finance",
      "Bitcoin",
      "Business",
      "Car Insurance",
      "China",
      "Climate Change",
      "Cocoa",
      "commodity",
      "Crypto Currency",
      "Decorating",
      "Design",
      "Interiors",
      "Make it Modern",
      "DIgital Currency",
      "Ecommerce",
      "Economy",
      "Education",
      "employment",
      "Energy",
      "Entrepreneurship",
      "Environment",
      "Europe",
      "Events",
      "Fashion",
      "Featured",
      "finance",
      "Fintech",
      "Food and Drinks",
      "Gadgets",
      "Ghana",
      "Global 360",
      "Austria",
      "brazil",
      "Germany",
      "India",
      "Mexico",
      "Philippines",
      "Russia",
      "Saudi Arabia",
      "South Korea",
      "Thailand",
      "Ukraine",
      "United Arab Emirates (UAE)",
      "Greater Accra Region - Accra",
      "Health and Wellness",
      "How To Spend",
      "Bitcoin",
      "Credit Cards",
      "Property and Mortages",
      "Water",
      "Hydroelectricity",
      "Insurance",
      "Internet Plans",
      "Investment",
      "Investor Activity",
      "Israel",
      "Jobs & Opportunities",
      "Jobs",
      "Kenya",
      "Level Up",
      "Life Insurance",
      "Lifestyle",
      "Recipes",
      "Travel",
      "Living Airspace",
      "Water Life",
      "local",
      "Making the news",
      "Markets",
      "Matters Arising",
      "Mining",
      "Mobile Phones",
      "Music",
      "News",
      "Nigeria",
      "On The Ground",
      "Opportunity",
      "Opportunity and Scholarships",
      "scholarship",
      "People and Culture",
      "Expat Communities In Ghana",
      "Photography",
      "Remote Working",
      "Renewable Energy",
      "Nuclear Energy",
      "Solar",
      "Senegal",
      "SMEs",
      "Sport",
      "Startup and Funding",
      "Stock Market",
      "Surveillance Africa",
      "France",
      "Ivory Coast",
      "Zimbabwe",
      "Sustainability",
      "Food Security",
      "Tanzania",
      "Tech On The Move",
      "Technology",
      "Cyber Security",
      "Mobile Money",
      "Telecom",
      "Travel In Style",
      "Uncategorised",
      "Uncategorized",
      "United Kingdom",
      "Video",
      "Volta Region - Ho",
      "What’s On",
      "Creative",
      "Culture",
      "Entertainment",
      "Legal Affairs",
      "Women With Skills",
    ],
    instructions:
      "Main is usually Headline. Choose 1-2 main categories from Headline, Making the news, Startup and Funding, Investor Activity, Scramble For Africa. Use up to 3 secondary categories, specific countries when relevant, and never use Uncategorised/Uncategorized.",
  },
};

export function getCategoryRule(website: CategoryRuleWebsite) {
  const key = Object.keys(WEBSITE_RULES).find(
    (k) =>
      website.url?.toLowerCase().includes(k) ||
      website.name?.toLowerCase().includes(k)
  );
  return key ? WEBSITE_RULES[key] : null;
}
